environment:
  nodejs_version: "12"

platform:
  - x86
  - x64

init:
  - git config --global core.autocrlf true

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt hardwario-cert.p12.enc -out hardwario-cert.p12 -secret %enc_secret%
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install node-pre-gyp -g
  - npm install electron-builder -g
  - npm install
  - npm rebuild node-sass

build_script:
  - if "%platform%" == "x86" npm run package-win32
  - if "%platform%" == "x64" npm run package-win64
  - cd release
  - dir
  - ps: >-
      $platform = Get-ChildItem Env:PLATFORM

      $platform = $platform.value

      if($platform -eq "x86") { Dir *.exe | Rename-Item -NewName {$_.BaseName + "-32bit" + $_.Extension} }

      if($platform -eq "x64") { Dir *.exe | Rename-Item -NewName {$_.BaseName + "-64bit" + $_.Extension} }

  - dir

artifacts:
  - path: release\*.exe

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

deploy:
- provider: GitHub
  auth_token:
    secure: 4cB5zdGSNXfNYzHtKibmbocO8WNtWe1g8090t4dUOuL7Y4u6/xjwv/0IwzrIWFK6
  artifact: /.*\.exe/
  force_update: true
  on:
    appveyor_repo_tag: true
