environment:
  nodejs_version: "10"

platform:
  - x86

init:
  - git config --global core.autocrlf true

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install node-pre-gyp -g
  - npm install electron-builder -g
  - npm install

build_script:
  - if "%platform%" == "x86" npm run package-win
  - dir release

artifacts:
  - path: release\*.exe

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

deploy:
- provider: GitHub
  auth_token:
    secure: 4cB5zdGSNXfNYzHtKibmbocO8WNtWe1g8090t4dUOuL7Y4u6/xjwv/0IwzrIWFK6
  artifact: release\*.exe
  force_update: true
  on:
    appveyor_repo_tag: true
