language: node_js

node_js:
  - "12"

os:
  - linux
  - osx

env:
  matrix:
  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="12"

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - node --version
  - node -p 'process.platform + "@" + process.arch'
  - npm --version
  - npm install node-pre-gyp -g
  - npm install node-abi@2.13.0 -g
  - npm install electron-builder -g

install:
  - npm install

script:
  - mkdir bin
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ENMON_URL=$(curl -s https://api.github.com/repos/hardwario/enmon/releases/latest | grep browser_download_url | grep linux | head -n 1 | cut -d '"' -f 4)
      curl -o bin/enmon "$ENMON_URL"
      chmod +x bin/enmon

      npm run package-linux64;
      npm run package-linux-appimage;

      cp release/*.deb .
      rename -v "s/linux/ubuntu/" *.deb
      mv *.deb release

      cp release/*.tar.gz .
      rename -v "s/linux/ubuntu/" *.tar.gz
      mv *.tar.gz release

      if [[ "$ARCH" == "x64" ]]; then
        cp release/*.AppImage .
        rename -v "s/linux/ubuntu/" *.AppImage
        mv *.AppImage release
      fi
    fi

  - cp -rfv patch/* ./

  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ENMON_URL=$(curl -s https://api.github.com/repos/hardwario/enmon/releases/latest | grep browser_download_url | grep darwin | head -n 1 | cut -d '"' -f 4)
      curl -o bin/enmon "$ENMON_URL"
      chmod +x bin/enmon

      npm run package-mac;
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libzmq-dev
      - libkrb5-dev
      - bc
      - bsdtar
      - curl

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

deploy:
  provider: releases
  file:
    - release/*.deb
    - release/*.AppImage
    - release/*.snap
    - release/*.dmg
    - release/*.tar.gz
  file_glob: true
  skip_cleanup: true
  api_key: ${GITHUB_KEY}
  on:
    tags: true
