language: node_js

node_js:
  - "16"

os:
  - linux
  - osx

env:
  matrix:
  - BINARY_BUILDER="true" TRAVIS_NODE_VERSION="16"

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - node --version
  - node -p 'process.platform + "@" + process.arch'
  - npm --version
  - npm install node-pre-gyp -g
  - mkdir bin
  - node download-enmon.js
  - chmod +x bin/enmon

install:
  - npm install
  - npm audit fix

script:
  - cp -rfv patch/* ./
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run package-linux64;
      npm run package-linux-appimage;

      cp release/*.deb .
      rename -v "s/linux/ubuntu/" *.deb
      mv *.deb release

      cp release/*.tar.gz .
      rename -v "s/linux/ubuntu/" *.tar.gz
      mv *.tar.gz release

      if [[ "$ARCH" == "x64" ]]; then
        cp release/*.AppImage .
        rename -v "s/linux/ubuntu/" *.AppImage
        mv *.AppImage release
      fi
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm run package-mac;
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
      - libzmq-dev
      - libkrb5-dev
      - bc
      - bsdtar
      - curl

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

deploy:
  provider: releases
  file:
    - release/*.deb
    - release/*.AppImage
    - release/*.snap
    - release/*.dmg
    - release/*.tar.gz
  file_glob: true
  skip_cleanup: true
  api_key: ${GITHUB_KEY}
  on:
    tags: true
