language: node_js

node_js:
  - node

os:
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install electron-installer-dmg -g ; fi
  - npm install node-pre-gyp -g
  - npm install electron-builder -g

install:
  - npm install

script:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run package-linux;
    fi

  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm run package-mac;
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libzmqpp-dev
      - bc

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

deploy:
  provider: releases
  file:
    - release/*.deb
    - release/*.AppImage
    - release/*.dmg
  file_glob: true
  skip_cleanup: true
  api_key: ${GITHUB_KEY}
  on:
    tags: true
