name: CI

on:
  push:
    branches: [ main, master, update ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          environment: linux

    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install node-gyp
      run: npm install --global node-gyp@latest

    - name: Install
      run: npm install

    - name: Prepare
      run: |
        npm run download-enmon
        npm run patch

    - name: Build for Linux
      if: matrix.environment == 'linux'
      run: |
          npm run package-linux64
          npm run package-linux-appimage
          chmod +x release/*.AppImage

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release ${{ matrix.os }}
        path: |
          release/*.deb
          release/*.AppImage
          release/*.snap
          release/*.tar.gz

    - name: Publish to GitHub Releases
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          release/*.deb
          release/*.AppImage
          release/*.snap
          release/*.tar.gz
